language: python
python:
  - "3.9"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8 coverage

script:
  - flake8 .
  - coverage run manage.py test
  - coverage report

# branches:
#   only:
#     - travis-ci-setup