language: python
python:
  - "3.11"

# Cache pip dependencies
cache: pip

# Install dependencies
install:
  - pip install -r requirements.txt

# Run tests and code quality checks
script:
  # Run Django tests
  - python manage.py test
  
  # Check code formatting with black
  - black --check .
  
  # Run flake8 linter
  - flake8 .
  
  # Run coverage analysis
  - coverage run --source='.' manage.py test
  - coverage report
  - coveralls

# Deploy to AWS Elastic Beanstalk on successful build
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: swe1-app
  env: swe1-env2
  # bucket_name: elasticbeanstalk-us-east-1-123456789012  # Commented out - let Travis auto-detect
  on:
    branch: deployment
    condition: $TRAVIS_PYTHON_VERSION = "3.11"

# Environment variables (you'll need to set these in Travis CI settings)
env:
  global:
    - DJANGO_DEBUG=0
    - SQLITE_NAME=/tmp/db.sqlite3
